[project]
name = "fastmcp-00"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.5",
    "flask>=3.1.2",
    "mypy>=1.18.2",
    "openai>=2.6.0",
]

[[tool.uv.index]]
url = "https://pypi.mirrors.ustc.edu.cn/simple"
